language: ruby
rvm:
- 2.1.2
- 2.2.2
addons:
  code_climate:
    repo_token:
      secure: G4bpiNUwVTTksk5nncmXcjMWh84uB3YbZwZsCqBROpjHOwaWcHDDID7OPWbl8Yp3x23Q9tj5oEI1i8+zei+jsk1AM5nB30XgAbIVQtv0qcahnDLrMNpWs4ubvBEw3yjwKRslqCD7WDC/lk8eYYmjJ6GyaIDeW8rJbITIkHTk4tKCjXFQRinUClWFfgg+rJSTyUqNqo3+aPaxDUvSeermOKK3jTQp9y1IsRFEbwtLUqliZ3rCgvhj43H4pQ0gDqsmtDqnuHgKBikm9D7+Gf6SbFyAMfy+XpHWlEXLjwwUVlTcSASB6cQ/v0ilJlLSzgaGoTgb6nBbLA3q/cvWTS3O5QEYfWnhzIlmoDBZXVRHWTcR1WpIXF10J5KT/UH+nHCOFGIefriMPWr6LZou1LMZrjY5hJLCeXxgM5xBF3MTAgiQd9cLlzzirCGzN9GGBOZsdDENG74IZPGpmKUPBm7OXjsrLc7rRIoPg92bMuDlBejU0RUWMDTjmrLvgLJM6R6ZdWQ6Ahf9YkLM7apDtVj3DFjOBX2oQuynq9ZuZ9dfhu49MME/7qeIQZD6HQqZixq9Zn8n2tFFvAMrIbeZKc5lZz5TumHiukouh6Jmq9e4issca9J4hV/hFlQ30Ds2plabbgzliISQlQEGh0oUBog3sW1prNnxkcfN+gO7uCHTBaI=